config/routes.rb
Rails.application.routes.draw do
  get 'permission/index'
  resources :users
  resources :resources
  root 'resources#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/permission.rb
class Permission < ApplicationRecord
  belongs_to :resource
  # has_and_belongs_to_many :users
  has_many :permissions_users
  has_many :users, through: :permissions_users

  def name_with_resource
    "#{resource.name} - #{name}"
  end
end

app/models/permission_user.rb
class PermissionUser < ApplicationRecord
  belongs_to :user
  belongs_to :permission
end

app/models/resource.rb
class Resource < ApplicationRecord
  has_many :permissions
  accepts_nested_attributes_for :permissions, reject_if: :all_blank, allow_destroy: true
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ApplicationRecord
  has_and_belongs_to_many :roles
  # has_and_belongs_to_many :permissions
  has_many :permission_users
  has_many :permissions, through: :permission_users
  has_many :resources, through: :permissions
  accepts_nested_attributes_for :permission_users, reject_if: :all_blank, allow_destroy: true

  validates :first_name, :last_name, :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  Fluenta::CommonUtilities::Controllers::Select2::AUTOCOMPLETE_LIMIT = 25
  include Fluenta::CommonUtilities::Controllers::Select2
end

app/controllers/permission_controller.rb
class PermissionController < ApplicationController
  def index
    @permissions = Permission
                       .joins(:resource)
                       .where('permissions.name ilike :term OR resources.name ilike :term', term: "%#{params[:q]}%")
                       .limit(Fluenta::CommonUtilities::Controllers::Select2::AUTOCOMPLETE_LIMIT)
                       .offset(offset_from_params)

    render json: @permissions,
           each_serializer: Select2::CommonSerializer,
           adapter: :json,
           text_attribute_name: 'name_with_resource',
           meta_key: 'pagination',
           meta: meta_attributes(@permissions)
  end
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
  before_action :set_resource, only: [:show, :edit, :update, :destroy]

  # GET /resources
  # GET /resources.json
  def index
    respond_to do |format|
      format.html
      format.json { render json: ResourceDatatable.new(params) }
    end
  end

  # GET /resources/1
  # GET /resources/1.json
  def show
  end

  # GET /resources/new
  def new
    @resource = Resource.new
  end

  # GET /resources/1/edit
  def edit
  end

  # POST /resources
  # POST /resources.json
  def create
    @resource = Resource.new(resource_params)

    respond_to do |format|
      if @resource.save
        format.html { redirect_to @resource, notice: 'Resource was successfully created.' }
        format.json { render :show, status: :created, location: @resource }
      else
        format.html { render :new }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resources/1
  # PATCH/PUT /resources/1.json
  def update
    respond_to do |format|
      if @resource.update(resource_params)
        format.html { redirect_to @resource, notice: 'Resource was successfully updated.' }
        format.json { render :show, status: :ok, location: @resource }
      else
        format.html { render :edit }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resources/1
  # DELETE /resources/1.json
  def destroy
    @resource.destroy
    respond_to do |format|
      format.html { redirect_to resources_url, notice: 'Resource was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resource
      @resource = Resource.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resource_params
      params.require(:resource).permit(:name, :location, :description, permissions_attributes: [:id, :name, :_destroy])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    respond_to do |format|
      format.html
      format.json { render json: UserDatatable.new(params) }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user.permissions.includes(:resource)
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, permission_users_attributes: [:permission_id, :id, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/permission_helper.rb
module PermissionHelper
end

app/helpers/permissions_helper.rb
module PermissionsHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
    <meta charset="utf-8"/>
    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
    <meta content="IE=edge" http-equiv="X-UA-Compatible"/>
    <title>Fluenta</title>
 
    <%= stylesheet_link_tag 'fluenta/layout/application-full', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    
  </head>
  <body class="skin-fl" >
    <!-- Wrapper
    -->
    <div id="wrapper">
      <!-- Navigation
      -->
      <%= render 'layouts/fluenta/layout/navigation' %>
      <!-- Page wraper
      -->
      <div class="gray-bg" id="page-wrapper">
        <!-- Page wrapper
        -->
        <%= render 'layouts/fluenta/layout/topnavbar' %>
        <%= render 'layouts/fluenta/layout/head_row' %>
        <%= render 'layouts/fluenta/layout/flash_messages' %>
        <!-- Main view
        -->
        <div class="wrapper wrapper-content">
          <div class="row">
            <% if content_for?(:row) %>
              <%= yield :row %>
            <% else %>
              <div class="col-sm-12">
                <div class="ibox">
                  <% if content_for?(:ibox_title) %>
                    <div class="ibox-title">
                      <%= yield :ibox_title %>
                    </div>
                  <% end %>
                  <% if content_for?(:ibox_content) %>
                    <%= yield :ibox_content %>
                  <% else %>
                    <div class="ibox-content">
                      <%= yield %>
                    </div>
                  <% end %>
                  <% if content_for?(:ibox_footer) %>
                    <div class="ibox-footer">
                      <%= yield :ibox_footer %>
                    </div>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
        <!-- Footer
        -->
        <%= render 'layouts/fluenta/layout/footer' %>
      </div>
      <!-- End page wrapper
      -->
    </div>
    <%= render 'layouts/fluenta/layout/embed_go' %>
    <%= content_for :bottom_scripts %>
    <!-- End wrapper
    -->
    <div id="modal-holder"></div>
  </body>
</html>

app/views/layouts/fluenta/layout/_head_row.html.erb
<div class="row wrapper border-bottom white-bg page-heading" data-turbolinks-permanent>
  <div class="col-lg-10">
    <h2>
      <%= yield :title %>
    </h2>
    <% unless content_for?(:breadcrumb) %>
      <ol class="breadcrumb">
        
      </ol>
    <% end %>
    <%= yield(:breadcrumb) if content_for?(:breadcrumb) %>
  </div>
  <div class="col-lg-2"></div>
</div>

app/views/layouts/fluenta/layout/_navigation.html.erb
<nav class='navbar-default navbar-static-side' data-turbolinks-permanent>
  <div class='sidebar-collapse'>
    <ul class='nav metismenu' id='side-menu'>
      <li>
        <%= link_to "Resources", resources_path %>
      </li>
      <li>
        <%= link_to "Users", users_path %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/fluenta/layout/_topnavbar.html.erb
<div class="row border-bottom" data-turbolinks-permanent>
  <div class="navbar-header visible-xs">
    <a class="navbar-minimalize minimalize-styl-2 btn btn-primary" href="#">
      <i class="fa fa-bars"></i>
    </a>
  </div>
  <ul class="nav navbar-top-links navbar-left m-t-md m-l-xs hidden-xs" id="system-messages"></ul>
  <ul class="nav navbar-top-links navbar-right">
    <li>
      <span id="timeField"></span>
    </li>
    <li>
      <%= link_to '#' do %>
        <%= fa_icon 'sign-out' %>
        <%= t('header.logout') %>
      <% end %>
    </li>
  </ul>
</div>

app/views/permission/index.html.haml
%h1 Permission#index
%p Find me in app/views/permission/index.html.haml

app/views/resources/_form.html.erb
<%= simple_form_for(@resource) do |form| %>
  
  <%= form.input :name %>
  <%= form.input :location %>
  <%= form.input :description %>
  
  <h4>Permissions</h4>
  <div data-controller="nested-form">
    <template data-target="nested-form.template">
      <%= form.simple_fields_for :permissions, Permission.new, child_index: 'NEW_RECORD' do |permission| %>
        <%= render "permission_fields", form: permission %>
      <% end %>
    </template>

    <%= form.simple_fields_for :permissions do |permission| %>
      <%= render "permission_fields", form: permission %>
    <% end %>

    <div class="mb-3" data-target="nested-form.links">
      <%= link_to "+ Add Permission", "#", class: "btn btn-xs btn-white", data: { action: "click->nested-form#add_association" } %>
    </div>
  </div>

  <div class="actions m-t-lg">
    <%= form.submit class: 'btn btn-primary' %>
    <%= link_to 'Back', resources_path, class: 'btn btn-white' %>
  </div>
<% end %>

app/views/resources/_permission_fields.html.erb
 <%= content_tag :div, class: "nested-fields", data: { new_record: form.object.new_record? } do %>
   <div class="form-group">
     <%= form.hidden_field :id %>
     <%= form.label :name %>
     <%= form.text_field :name, class: 'form-control' %>
     <small><%= link_to "Remove", "#", data: { action: "click->nested-form#remove_association" } %></small>
   </div>

   <%= form.hidden_field :_destroy %>
 <% end %>

app/views/resources/edit.html.erb
<% content_for :ibox_title do %>
  <h1>Editing Resource</h1>
<% end %>

<%= render 'form', resource: @resource %>

app/views/resources/index.html.erb
<% content_for :ibox_title do %>
  <h1>Resources</h1>
<% end %>

<table id="ajax-datatable" class="table"
  data-controller="datatable"
  data-datatable-config="<%= { 
    debug: true,
    serverSide: true,
    ajax: resources_path,
    dom: '<"html5buttons"B><lfr>t<ip>',
    stateSave: true,
    pageLength: 25,
    columns: [
      {title: 'Name', data: 'name', width: '30%' },
      {title: 'Location', data: 'location', },
      {title: 'Actions', data: 'dt_actions', },
    ],
  }.to_json %>"
>
</table>

<%= link_to 'New Resource', new_resource_path, class: 'btn btn-primary' %>

app/views/resources/new.html.erb
<% content_for :ibox_title do %>
  <h1>New Resource</h1>
<% end %>

<%= render 'form', resource: @resource %>

app/views/resources/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @resource.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @resource.location %>
</p>

<p>
  <strong>Description:</strong>
  <%= @resource.description %>
</p>

<%= link_to 'Edit', edit_resource_path(@resource), class: 'btn btn-primary' %>
<%= link_to 'Back', resources_path, class: 'btn btn-white' %>

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |form| %>
  <%= form.input :first_name %>
  <%= form.input :last_name %>
  <%= form.input :email %>


  <h4>Resources</h4>
  <div data-controller="nested-form">
    <template data-target="nested-form.template">
      <%= form.simple_fields_for :permission_users, PermissionUser.new(user_id: form.object.try(:id)), child_index: 'NEW_RECORD' do |permission_user| %>
        <%= render "permission_user_fields", form: permission_user %>
      <% end %>
    </template>

    <%= form.simple_fields_for :permission_users do |permission_user| %>
      <%= render "permission_user_fields", form: permission_user %>
    <% end %>

    <div class="mb-3" data-target="nested-form.links">
      <%= link_to "+ Add permission", "#", class: "btn btn-xs btn-white", data: { action: "click->nested-form#add_association" } %>
    </div>
  </div>

  <div class="actions m-t-lg">
    <%= form.submit class: 'btn btn-primary' %>
    <%= link_to 'Back', users_path, class: 'btn btn-white' %>
  </div>
<% end %>

app/views/users/_permission_user_fields.html.erb
<%= content_tag :div, class: "nested-fields", data: { new_record: form.object.new_record? } do %>
  <%= form.input :permission_id, collection: form.object.permission_id.present? ? [[form.object.permission.name_with_resource, form.object.permission.id, { selected: true }]] : [], input_html: { class: 'select2', data: { 'ajax--dataType' => :json, 'ajax--url' => permission_index_path, controller: 'select2' } } %>
  <small><%= link_to "Remove", "#", data: { action: "click->nested-form#remove_association" } %></small>
  <%= form.hidden_field :_destroy %>
<% end %>

app/views/users/edit.html.erb
<% content_for :ibox_title do %>
  <h1>Editing User</h1>
<% end %>

<%= render 'form', user: @user %>

app/views/users/index.html.erb
<% content_for :ibox_title do %>
  <h1>Users</h1>
<% end %>

<table id="ajax-datatable" class="table"
  data-controller="datatable"
  data-datatable-config="<%= { 
    debug: true,
    serverSide: true,
    deferRender: true,
    ajax: users_path,
    dom: '<"html5buttons"B><lfr>t<ip>',
    stateSave: true,
    columns: [
      {title: 'First Name', data: 'first_name' },
      {title: 'Last name', data: 'last_name', },
      {title: 'Email', data: 'email', },
      {title: 'Actions', data: 'dt_actions', },
    ],
  }.to_json %>"
>
</table>

<br>

<%= link_to 'New User', new_user_path, class: 'btn btn-primary' %>

app/views/users/new.html.erb
<% content_for :ibox_title do %>
  <h1>New user</h1>
<% end %>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<table class='table'>
  <thead>
    <tr>
      <th>Resource</th>
      <th>Permission</th>
    </tr>
  </thead>
  <tbody>
    <%- @user.permissions.each do |permission| %>
      <tr>
        <td><%= permission.resource.name %></td>
        <td><%= permission.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_user_path(@user), class: 'btn btn-primary' %>
<%= link_to 'Back', users_path, class: 'btn btn-white' %>